// AUTO-GENERATED by scripts/sync-themes.ts – do not edit. Run `pnpm themes:sync` after adding a theme.
import type { ThemeManifest, ThemeModule } from "./types";
import m_bistro from "./bistro/manifest";
import m_classic from "./classic/manifest";
import m_modern from "./modern/manifest";

/** Theme manifests (pure data, safe to send to the dashboard). */
export const THEME_MANIFESTS: Record<string, ThemeManifest> = {
  "bistro": m_bistro,
  "classic": m_classic,
  "modern": m_modern,
};

/** Lazy theme modules – only the active theme's code is loaded per request. */
export const THEME_LOADERS: Record<string, () => Promise<ThemeModule>> = {
  "bistro": () => import("./bistro").then((m) => m.default),
  "classic": () => import("./classic").then((m) => m.default),
  "modern": () => import("./modern").then((m) => m.default),
};
