/**
 * Bundles the print starters (QR table cards, tents, posters – src/themes/print-starters/<key>/, real files) into a TS
 * module so they work in Next (Turbopack), tsx scripts and the standalone build without fs access at runtime.
 *
 *   pnpm themes:print-starters   (run after editing a print starter; fails on validation or render errors)
 *
 * Output: src/themes/print-starters/index.generated.ts
 */
import fs from "node:fs";
import path from "node:path";
import { validatePackage } from "../src/modules/theme-engine/validate";
import { renderPrintDocument, samplePrintViews } from "../src/modules/theme-engine/print";
import type { ThemeManifest, ThemePackage } from "../src/modules/theme-engine/types";

const ROOT = path.join(process.cwd(), "src", "themes", "print-starters");
const OUT = path.join(ROOT, "index.generated.ts");
const ORDER = ["minimal-a6", "elegant-tent", "bold-poster-a4", "kraft-a6", "neon-bar-a6"];

function walk(dir: string, base = dir): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? walk(p, base) : [path.relative(base, p).split(path.sep).join("/")];
  });
}

async function main() {
  const keys = fs
    .readdirSync(ROOT, { withFileTypes: true })
    .filter((e) => e.isDirectory() && fs.existsSync(path.join(ROOT, e.name, "manifest.json")))
    .map((e) => e.name)
    .sort((a, b) => (ORDER.indexOf(a) + 1 || 99) - (ORDER.indexOf(b) + 1 || 99) || a.localeCompare(b));

  let failed = false;
  const starters = [];
  for (const key of keys) {
    const dir = path.join(ROOT, key);
    const manifest = JSON.parse(fs.readFileSync(path.join(dir, "manifest.json"), "utf8")) as ThemeManifest;
    const files: Record<string, string> = {};
    for (const rel of walk(dir).sort()) {
      if (rel === "manifest.json" || rel.startsWith(".")) continue;
      files[rel] = fs.readFileSync(path.join(dir, rel), "utf8");
    }
    const pkg: ThemePackage = { manifest, files };
    const v = validatePackage(pkg);
    if (manifest.kind !== "print") v.errors.push({ message: 'manifest.kind must be "print"' });
    const r = await renderPrintDocument({ pkg, views: samplePrintViews(), assetBaseUrl: "https://veromenu.invalid", guestMessages: {}, mode: "preview" });
    if (!r.ok) v.errors.push(...r.errors.map((message) => ({ message: `render: ${message}` })));
    for (const e of r.errors) if (r.ok) v.warnings.push({ message: `render: ${e}` });
    if (v.errors.length) {
      failed = true;
      console.error(`✘ ${key}:`, v.errors);
    }
    for (const w of v.warnings) console.warn(`  ⚠ ${key}: ${w.file ? `${w.file}: ` : ""}${w.message}`);
    console.log(`${v.errors.length ? "✘" : "✔"} ${key} (${Object.keys(files).length} files, ${manifest.print?.format}/${manifest.print?.sheet})`);
    starters.push({ key, name: manifest.name, description: manifest.description ?? {}, pkg });
  }
  if (failed) process.exit(1);

  const ts = `// AUTO-GENERATED by scripts/build-print-starters.ts (pnpm themes:print-starters) – do not edit.
// Source: src/themes/print-starters/<key>/ (manifest.json, templates/, assets/, locales/)
import type { ThemePackage } from "@/modules/theme-engine/types";

export const PRINT_STARTERS: { key: string; name: string; description: Record<string, string>; pkg: ThemePackage }[] = ${JSON.stringify(starters, null, 2)};
`;
  fs.writeFileSync(OUT, ts);
  console.log(`→ ${path.relative(process.cwd(), OUT)}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
