/**
 * Self-hosted font library for studio themes (DSGVO / LG München 2022: never load fonts from Google).
 *
 *   pnpm themes:fonts
 *
 * Copies latin + latin-ext woff2 files of the selected weights from node_modules/@fontsource/* into
 * public/theme-fonts/<id>/ and generates
 *   - public/theme-fonts/fonts.css                     (all faces, relative URLs – studio font picker)
 *   - public/theme-fonts/LICENSES.txt                  (OFL attributions)
 *   - src/modules/theme-engine/fonts.generated.ts      (FONT_LIBRARY data, isomorphic)
 * The output is committed (served statically). Re-run after adding an @fontsource package.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const SRC = path.join(ROOT, "node_modules", "@fontsource");
const OUT = path.join(ROOT, "public", "theme-fonts");
const GEN = path.join(ROOT, "src", "modules", "theme-engine", "fonts.generated.ts");

const SUBSETS = ["latin", "latin-ext"] as const;
const WANTED_WEIGHTS = [400, 500, 600, 700, 800];
/** Fonts that are used as headline/display faces even though fontsource calls them sans-serif. */
const CATEGORY_OVERRIDE: Record<string, Category> = { "bebas-neue": "display", oswald: "display", righteous: "display" };

type Category = "sans" | "serif" | "display" | "script";
type Meta = { id: string; family: string; weights: number[]; styles: string[]; subsets: string[]; category: string; license?: { attribution?: string; type?: string } };

const mapCategory = (c: string): Category => (c === "serif" ? "serif" : c === "handwriting" ? "script" : c === "display" ? "display" : "sans");

function rangesFromCss(css: string, id: string, weight: number, style: string) {
  const out: Partial<Record<(typeof SUBSETS)[number], string>> = {};
  for (const subset of SUBSETS) {
    const re = new RegExp(`/\\* ${id}-${subset}-${weight}-${style} \\*/[\\s\\S]*?unicode-range:\\s*([^;]+);`);
    const m = css.match(re);
    if (m) out[subset] = m[1].trim();
  }
  return out;
}

function main() {
  if (!fs.existsSync(SRC)) throw new Error("node_modules/@fontsource not found – run pnpm install");
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  const fonts: { id: string; family: string; category: Category; weights: number[]; italic: number[]; ranges?: Record<string, string> }[] = [];
  const defaultRanges: Record<string, string> = {};
  const css: string[] = ["/* AUTO-GENERATED by scripts/build-theme-fonts.ts – self-hosted fonts for studio themes. */"];
  const licenses: string[] = ["Fonts in this folder are licensed under the SIL Open Font License 1.1 (https://openfontlicense.org).", ""];
  let bytes = 0;
  let files = 0;

  for (const dir of fs.readdirSync(SRC).sort()) {
    const metaFile = path.join(SRC, dir, "metadata.json");
    if (!fs.existsSync(metaFile)) continue;
    const meta = JSON.parse(fs.readFileSync(metaFile, "utf8")) as Meta;
    const id = meta.id;
    const category = CATEGORY_OVERRIDE[id] ?? mapCategory(meta.category);
    let weights = meta.weights.filter((w) => WANTED_WEIGHTS.includes(w));
    if (!weights.length) weights = [meta.weights.includes(400) ? 400 : meta.weights[0]];
    // italics only where they matter (serif body text) and keep the library small
    const italic = meta.styles.includes("italic") && category === "serif" ? weights.filter((w) => w === 400 || w === 700) : [];
    const faces = [...weights.map((w) => [w, "normal"] as const), ...italic.map((w) => [w, "italic"] as const)];
    const fontRanges: Record<string, string> = {};
    fs.mkdirSync(path.join(OUT, id), { recursive: true });

    for (const [w, style] of faces) {
      const cssFile = path.join(SRC, dir, style === "italic" ? `${w}-italic.css` : `${w}.css`);
      const ranges = fs.existsSync(cssFile) ? rangesFromCss(fs.readFileSync(cssFile, "utf8"), id, w, style) : {};
      for (const subset of SUBSETS) {
        const name = `${id}-${subset}-${w}-${style}.woff2`;
        const from = path.join(SRC, dir, "files", name);
        if (!fs.existsSync(from)) continue;
        fs.copyFileSync(from, path.join(OUT, id, name));
        bytes += fs.statSync(from).size;
        files++;
        const range = ranges[subset];
        if (range) {
          if (!defaultRanges[subset]) defaultRanges[subset] = range;
          if (range !== defaultRanges[subset]) fontRanges[subset] = range;
        }
        css.push(
          `@font-face{font-family:'${meta.family}';font-style:${style};font-weight:${w};font-display:swap;src:url(./${id}/${name}) format('woff2');${range ? `unicode-range:${range};` : ""}}`,
        );
      }
    }
    fonts.push({ id, family: meta.family, category, weights, italic, ...(Object.keys(fontRanges).length ? { ranges: fontRanges } : {}) });
    licenses.push(`${meta.family} (${id}): ${meta.license?.attribution ?? meta.license?.type ?? "OFL-1.1"}`);
  }

  fs.writeFileSync(path.join(OUT, "fonts.css"), css.join("\n") + "\n");
  fs.writeFileSync(path.join(OUT, "LICENSES.txt"), licenses.join("\n") + "\n");

  const ts = `// AUTO-GENERATED by scripts/build-theme-fonts.ts (pnpm themes:fonts) – do not edit.
// Files: public/theme-fonts/<id>/<id>-<subset>-<weight>-<style>.woff2

export const FONT_SUBSETS = ${JSON.stringify(SUBSETS)} as const;

/** Default unicode-range per subset (fonts with different ranges carry their own). */
export const FONT_SUBSET_RANGES: Record<string, string> = ${JSON.stringify(defaultRanges, null, 2)};

export const FONT_DATA: { id: string; family: string; category: "sans" | "serif" | "display" | "script"; weights: number[]; italic: number[]; ranges?: Record<string, string> }[] = ${JSON.stringify(fonts, null, 2)};
`;
  fs.writeFileSync(GEN, ts);
  console.log(`✔ ${fonts.length} fonts, ${files} files, ${(bytes / 1024 / 1024).toFixed(2)} MB → public/theme-fonts`);
}

main();
