/**
 * Bundles the starter themes (src/themes/starters/<key>/ – real files) into a TS module so they work in
 * Next (Turbopack), tsx scripts and the standalone build without fs access at runtime.
 *
 *   pnpm themes:starters        (run after editing a starter; fails on validation errors)
 *
 * Output: src/themes/starters/index.generated.ts
 */
import fs from "node:fs";
import path from "node:path";
import { validatePackage } from "../src/modules/theme-engine/validate";
import type { ThemeManifest, ThemePackage } from "../src/modules/theme-engine/types";

const ROOT = path.join(process.cwd(), "src", "themes", "starters");
const OUT = path.join(ROOT, "index.generated.ts");
const ORDER = ["atelier", "trattoria", "neon-bar", "cafe-pastell", "street-food"];

function walk(dir: string, base = dir): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? walk(p, base) : [path.relative(base, p).split(path.sep).join("/")];
  });
}

function main() {
  const keys = fs
    .readdirSync(ROOT, { withFileTypes: true })
    .filter((e) => e.isDirectory() && fs.existsSync(path.join(ROOT, e.name, "manifest.json")))
    .map((e) => e.name)
    .sort((a, b) => (ORDER.indexOf(a) + 1 || 99) - (ORDER.indexOf(b) + 1 || 99) || a.localeCompare(b));

  let failed = false;
  const starters = keys.map((key) => {
    const dir = path.join(ROOT, key);
    const manifest = JSON.parse(fs.readFileSync(path.join(dir, "manifest.json"), "utf8")) as ThemeManifest;
    const files: Record<string, string> = {};
    for (const rel of walk(dir).sort()) {
      if (rel === "manifest.json" || rel.startsWith(".")) continue;
      files[rel] = fs.readFileSync(path.join(dir, rel), "utf8");
    }
    const pkg: ThemePackage = { manifest, files };
    const v = validatePackage(pkg);
    if (!v.ok) {
      failed = true;
      console.error(`✘ ${key}:`, v.errors);
    }
    for (const w of v.warnings) console.warn(`  ⚠ ${key}: ${w.file ? `${w.file}: ` : ""}${w.message}`);
    console.log(`${v.ok ? "✔" : "✘"} ${key} (${Object.keys(files).length} files)`);
    return { key, name: manifest.name, description: manifest.description ?? {}, pkg };
  });
  if (failed) process.exit(1);

  const ts = `// AUTO-GENERATED by scripts/build-theme-starters.ts (pnpm themes:starters) – do not edit.
// Source: src/themes/starters/<key>/ (manifest.json, templates/, assets/, locales/)
import type { ThemePackage } from "@/modules/theme-engine/types";

export const STARTER_THEMES: { key: string; name: string; description: Record<string, string>; pkg: ThemePackage }[] = ${JSON.stringify(starters, null, 2)};
`;
  fs.writeFileSync(OUT, ts);
  console.log(`→ ${path.relative(process.cwd(), OUT)}`);
}

main();
