/**
 * Theme registry generator – `pnpm themes:sync`.
 * Scans src/themes/<id>/manifest.ts (+ index.tsx) and writes src/themes/registry.generated.ts.
 * Validates: folder name = manifest.id, required metadata, unique field keys, valid defaults.
 */
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const THEMES = path.join(ROOT, "src", "themes");
const OUT = path.join(THEMES, "registry.generated.ts");

type Field = { key: string; type: string; default: unknown; options?: unknown[]; min?: number; max?: number };
type Manifest = { id: string; name: string; version: string; author: string; description: Record<string, string>; preview: string; fields: Field[] };

async function main() {
  const dirs = fs
    .readdirSync(THEMES, { withFileTypes: true })
    .filter((d) => d.isDirectory() && fs.existsSync(path.join(THEMES, d.name, "manifest.ts")))
    .map((d) => d.name)
    .sort();

  const errors: string[] = [];
  const ids: string[] = [];
  for (const dir of dirs) {
    if (!/^[a-z][a-z0-9-]*$/.test(dir)) {
      errors.push(`${dir}: folder name must be lowercase (a-z, 0-9, -)`);
      continue;
    }
    if (!fs.existsSync(path.join(THEMES, dir, "index.tsx"))) errors.push(`${dir}: missing index.tsx`);
    const mod = (await import(pathToFileURL(path.join(THEMES, dir, "manifest.ts")).href)) as { default?: Manifest | { default?: Manifest } };
    const m = ((mod.default as { default?: Manifest })?.default ?? mod.default) as Manifest | undefined;
    if (!m) {
      errors.push(`${dir}: manifest.ts needs a default export`);
      continue;
    }
    if (m.id !== dir) errors.push(`${dir}: manifest.id "${m.id}" must equal the folder name`);
    for (const k of ["name", "version", "author", "preview"] as const) if (!m[k]) errors.push(`${dir}: manifest.${k} is required`);
    if (!m.description?.de || !m.description?.en) errors.push(`${dir}: description needs at least de + en`);
    if (m.preview && !fs.existsSync(path.join(ROOT, "public", m.preview.replace(/^\//, "")))) errors.push(`${dir}: preview image ${m.preview} not found in public/`);
    const keys = new Set<string>();
    for (const f of m.fields ?? []) {
      if (keys.has(f.key)) errors.push(`${dir}: duplicate field key "${f.key}"`);
      keys.add(f.key);
      if (!["color", "select", "font", "boolean", "range"].includes(f.type)) errors.push(`${dir}: field "${f.key}" has unknown type ${f.type}`);
      if (f.type === "range" && (typeof f.default !== "number" || f.default < (f.min ?? 0) || f.default > (f.max ?? 0)))
        errors.push(`${dir}: field "${f.key}" default out of range`);
      if (f.type === "color" && !/^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(String(f.default))) errors.push(`${dir}: field "${f.key}" default must be a hex colour`);
    }
    ids.push(dir);
  }
  if (!ids.includes("classic")) errors.push('the "classic" theme is required (fallback for unknown theme ids)');
  if (errors.length) {
    console.error("Theme sync failed:\n  - " + errors.join("\n  - "));
    process.exit(1);
  }

  const v = (id: string) => `m_${id.replace(/-/g, "_")}`;
  const out = `// AUTO-GENERATED by scripts/sync-themes.ts – do not edit. Run \`pnpm themes:sync\` after adding a theme.
import type { ThemeManifest, ThemeModule } from "./types";
${ids.map((id) => `import ${v(id)} from "./${id}/manifest";`).join("\n")}

/** Theme manifests (pure data, safe to send to the dashboard). */
export const THEME_MANIFESTS: Record<string, ThemeManifest> = {
${ids.map((id) => `  ${JSON.stringify(id)}: ${v(id)},`).join("\n")}
};

/** Lazy theme modules – only the active theme's code is loaded per request. */
export const THEME_LOADERS: Record<string, () => Promise<ThemeModule>> = {
${ids.map((id) => `  ${JSON.stringify(id)}: () => import("./${id}").then((m) => m.default),`).join("\n")}
};
`;
  fs.writeFileSync(OUT, out);
  console.log(`✓ ${ids.length} themes registered: ${ids.join(", ")} → ${path.relative(ROOT, OUT)}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
