/**
 * Self-hosted font library (isomorphic). Files live in public/theme-fonts (generated by
 * `pnpm themes:fonts`), never on Google servers (DSGVO, LG München 2022).
 */
import { FONT_DATA, FONT_SUBSETS, FONT_SUBSET_RANGES } from "./fonts.generated";

export type FontInfo = {
  id: string;
  family: string;
  category: "sans" | "serif" | "display" | "script";
  weights: number[];
  /** Weights that also ship an italic face. */
  italic?: number[];
};

export const FONT_LIBRARY: FontInfo[] = FONT_DATA.map(({ id, family, category, weights, italic }) => ({ id, family, category, weights, italic }));

const BY_ID = new Map(FONT_DATA.map((f) => [f.id, f]));

export const isFontId = (id: unknown): id is string => typeof id === "string" && BY_ID.has(id);
export const getFont = (id: string): FontInfo | undefined => BY_ID.get(id);

const FALLBACK: Record<FontInfo["category"], string> = {
  sans: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Noto Sans', sans-serif",
  serif: "ui-serif, Georgia, 'Noto Serif', serif",
  display: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
  script: "'Segoe Script', 'Brush Script MT', cursive",
};
export const SYSTEM_FONT_STACK = FALLBACK.sans;

/** CSS font-family value with system fallbacks (cover Arabic, CJK, Cyrillic, Greek …). */
export function fontStack(id: unknown): string {
  const f = typeof id === "string" ? BY_ID.get(id) : undefined;
  return f ? `'${f.family}', ${FALLBACK[f.category]}` : SYSTEM_FONT_STACK;
}

/** Public URL path of a font file (relative to the app origin). */
export const fontFilePath = (id: string, subset: string, weight: number, style: "normal" | "italic") =>
  `/theme-fonts/${id}/${id}-${subset}-${weight}-${style}.woff2`;

/** @font-face rules for the given font ids (absolute URLs – the theme frame has an opaque origin). */
export function fontFaceCss(ids: Iterable<string>, assetBaseUrl: string): string {
  const base = assetBaseUrl.replace(/\/+$/, "");
  const out: string[] = [];
  for (const id of new Set(ids)) {
    const f = BY_ID.get(id);
    if (!f) continue;
    const faces = [...f.weights.map((w) => [w, "normal"] as const), ...f.italic.map((w) => [w, "italic"] as const)];
    for (const [w, style] of faces) {
      for (const subset of FONT_SUBSETS) {
        const range = f.ranges?.[subset] ?? FONT_SUBSET_RANGES[subset];
        out.push(
          `@font-face{font-family:'${f.family}';font-style:${style};font-weight:${w};font-display:swap;src:url(${base}${fontFilePath(id, subset, w, style)}) format('woff2');${range ? `unicode-range:${range};` : ""}}`,
        );
      }
    }
  }
  return out.join("\n");
}
