// AUTO-GENERATED by scripts/build-theme-fonts.ts (pnpm themes:fonts) – do not edit.
// Files: public/theme-fonts/<id>/<id>-<subset>-<weight>-<style>.woff2

export const FONT_SUBSETS = ["latin","latin-ext"] as const;

/** Default unicode-range per subset (fonts with different ranges carry their own). */
export const FONT_SUBSET_RANGES: Record<string, string> = {
  "latin": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
  "latin-ext": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
};

export const FONT_DATA: { id: string; family: string; category: "sans" | "serif" | "display" | "script"; weights: number[]; italic: number[]; ranges?: Record<string, string> }[] = [
  {
    "id": "abril-fatface",
    "family": "Abril Fatface",
    "category": "display",
    "weights": [
      400
    ],
    "italic": []
  },
  {
    "id": "amatic-sc",
    "family": "Amatic SC",
    "category": "script",
    "weights": [
      400,
      700
    ],
    "italic": []
  },
  {
    "id": "bebas-neue",
    "family": "Bebas Neue",
    "category": "display",
    "weights": [
      400
    ],
    "italic": []
  },
  {
    "id": "caveat",
    "family": "Caveat",
    "category": "script",
    "weights": [
      400,
      500,
      600,
      700
    ],
    "italic": []
  },
  {
    "id": "cormorant-garamond",
    "family": "Cormorant Garamond",
    "category": "serif",
    "weights": [
      400,
      500,
      600,
      700
    ],
    "italic": [
      400,
      700
    ]
  },
  {
    "id": "dm-sans",
    "family": "DM Sans",
    "category": "sans",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": []
  },
  {
    "id": "dm-serif-display",
    "family": "DM Serif Display",
    "category": "serif",
    "weights": [
      400
    ],
    "italic": [
      400
    ]
  },
  {
    "id": "eb-garamond",
    "family": "EB Garamond",
    "category": "serif",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": [
      400,
      700
    ]
  },
  {
    "id": "fraunces",
    "family": "Fraunces",
    "category": "serif",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": [
      400,
      700
    ]
  },
  {
    "id": "inter",
    "family": "Inter",
    "category": "sans",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": []
  },
  {
    "id": "josefin-sans",
    "family": "Josefin Sans",
    "category": "sans",
    "weights": [
      400,
      500,
      600,
      700
    ],
    "italic": []
  },
  {
    "id": "libre-baskerville",
    "family": "Libre Baskerville",
    "category": "serif",
    "weights": [
      400,
      500,
      600,
      700
    ],
    "italic": [
      400,
      700
    ]
  },
  {
    "id": "lobster",
    "family": "Lobster",
    "category": "display",
    "weights": [
      400
    ],
    "italic": []
  },
  {
    "id": "lora",
    "family": "Lora",
    "category": "serif",
    "weights": [
      400,
      500,
      600,
      700
    ],
    "italic": [
      400,
      700
    ]
  },
  {
    "id": "merriweather",
    "family": "Merriweather",
    "category": "serif",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": [
      400,
      700
    ]
  },
  {
    "id": "montserrat",
    "family": "Montserrat",
    "category": "sans",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": []
  },
  {
    "id": "nunito",
    "family": "Nunito",
    "category": "sans",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": []
  },
  {
    "id": "oswald",
    "family": "Oswald",
    "category": "display",
    "weights": [
      400,
      500,
      600,
      700
    ],
    "italic": []
  },
  {
    "id": "pacifico",
    "family": "Pacifico",
    "category": "script",
    "weights": [
      400
    ],
    "italic": []
  },
  {
    "id": "playfair-display",
    "family": "Playfair Display",
    "category": "serif",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": [
      400,
      700
    ]
  },
  {
    "id": "poppins",
    "family": "Poppins",
    "category": "sans",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": []
  },
  {
    "id": "raleway",
    "family": "Raleway",
    "category": "sans",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": []
  },
  {
    "id": "righteous",
    "family": "Righteous",
    "category": "display",
    "weights": [
      400
    ],
    "italic": []
  },
  {
    "id": "space-grotesk",
    "family": "Space Grotesk",
    "category": "sans",
    "weights": [
      400,
      500,
      600,
      700
    ],
    "italic": []
  },
  {
    "id": "work-sans",
    "family": "Work Sans",
    "category": "sans",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ],
    "italic": []
  }
];
